from django.urls import path

from apps.duties.views import (
    DutyScheduleListCreateAPIView,
    DutyScheduleUpdateAPIView,
    DutyScheduleCancelAPIView,
    DutyReplaceAPIView,
    InstructorMissingHoursAPIView,
    DutyCheckInAPIView,
    DutyCheckOutAPIView,
    InstructorMyAttendanceAPIView,
    InstructorMySchedulesAPIView,
    AdminInstructorPaymentsAPIView,
    InstructorMyPaymentsAPIView,
    InstructorMyPaymentColumnsAPIView,
    ComputeAllPaymentsAPIView,
    ComputePaymentAPIView,
    ApprovePaymentAPIView,
    PaymentColumnsAPIView,
    PaymentColumnCreateAPIView,
    PaymentColumnDeleteAPIView,
    PaymentColumnValueAPIView,
    MarkPaymentPaidAPIView,
    ExportInstructorPaymentsExcelAPIView,
)

urlpatterns = [
    path("", DutyScheduleListCreateAPIView.as_view(), name="duty-schedules"),
    path("<uuid:schedule_id>/update/", DutyScheduleUpdateAPIView.as_view(), name="duty-schedule-update"),
    path("<uuid:schedule_id>/cancel/", DutyScheduleCancelAPIView.as_view(), name="duty-schedule-cancel"),
    path("<uuid:schedule_id>/replace/", DutyReplaceAPIView.as_view(), name="duty-schedule-replace"),
    path("instructor/missing-hours/", InstructorMissingHoursAPIView.as_view(), name="instructor-missing-hours"),
    path("<uuid:schedule_id>/check-in/", DutyCheckInAPIView.as_view(), name="duty-schedule-checkin"),
    path("<uuid:schedule_id>/check-out/", DutyCheckOutAPIView.as_view(), name="duty-schedule-checkout"),
    path("instructor/attendance/", InstructorMyAttendanceAPIView.as_view(), name="instructor-attendance"),
    path("instructor/my-schedules/", InstructorMySchedulesAPIView.as_view(), name="instructor-my-schedules"),
    path("admin/instructor-payments/compute-all/", ComputeAllPaymentsAPIView.as_view(), name="compute-all-instructor-payments"),
    path("admin/instructor-payments/compute/", ComputePaymentAPIView.as_view(), name="compute-instructor-payment"),
    path("admin/instructor-payments/<uuid:payment_id>/approve/", ApprovePaymentAPIView.as_view(), name="approve-instructor-payment"),
    path("admin/instructor-payments/columns/", PaymentColumnsAPIView.as_view(), name="list-payment-columns"),
    path("admin/instructor-payments/columns/create/", PaymentColumnCreateAPIView.as_view(), name="create-payment-column"),
    path("admin/instructor-payments/columns/<uuid:column_id>/", PaymentColumnDeleteAPIView.as_view(), name="delete-payment-column"),
    path("admin/instructor-payments/<uuid:payment_id>/columns/<uuid:column_id>/", PaymentColumnValueAPIView.as_view(), name="set-payment-column-value"),
    path("admin/instructor-payments/<uuid:payment_id>/paid/", MarkPaymentPaidAPIView.as_view(), name="mark-instructor-payment-paid"),
    path("admin/instructor-payments/export/", ExportInstructorPaymentsExcelAPIView.as_view(), name="export-instructor-payments"),
    path("admin/instructor-payments/", AdminInstructorPaymentsAPIView.as_view(), name="admin-instructor-payments"),
    path("instructor/my-payments/", InstructorMyPaymentsAPIView.as_view(), name="instructor-my-payments"),
    path("instructor/my-payment-columns/", InstructorMyPaymentColumnsAPIView.as_view(), name="instructor-my-payment-columns"),
]